# Generated by Django 4.2.16 on 2026-03-23 15:59

from django.db import migrations, models
import django.db.models.deletion
import load_cdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
        ('data_cdf', '0002_wind_wi_h0_mfi_v01_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACE_AC_H0_MFI_v01_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day_of_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_elapsed_milliseconds_of_day', models.IntegerField(blank=True, null=True)),
                ('magnitude', load_cdf.models.Float32Field(blank=True, null=True)),
                ('bgsec_bx', load_cdf.models.Float32Field(blank=True, null=True)),
                ('bgsec_by', load_cdf.models.Float32Field(blank=True, null=True)),
                ('bgsec_bz', load_cdf.models.Float32Field(blank=True, null=True)),
                ('bgsm_bx', load_cdf.models.Float32Field(blank=True, null=True)),
                ('bgsm_by', load_cdf.models.Float32Field(blank=True, null=True)),
                ('bgsm_bz', load_cdf.models.Float32Field(blank=True, null=True)),
                ('q_flag', models.IntegerField(blank=True, null=True)),
                ('sc_pos_gse_x', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_y', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_z', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_x', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_y', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_z', load_cdf.models.Float32Field(blank=True, null=True)),
                ('cdf_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ACE_AC_H0_MFI_v01_data_data', to='load_cdf.cdffilestored')),
            ],
        ),
    ]
