# Generated by Django 4.2.16 on 2026-03-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cdf', '0003_ace_ac_h0_mfi_v01_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACE_AC_H0_MFI_v01_data',
        ),
    ]
