# Generated by Django 4.2.16 on 2026-03-24 13:48

from django.db import migrations, models
import django.db.models.deletion
import load_cdf.models


class Migration(migrations.Migration):

    dependencies = [
        ('load_cdf', '0001_initial'),
        ('data_cdf', '0004_delete_ace_ac_h0_mfi_v01_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIND_WI_K0_SWE_v01_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.BigIntegerField(blank=True, null=True)),
                ('delta_time', models.FloatField(blank=True, null=True)),
                ('time_pb5_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_day_of_year', models.IntegerField(blank=True, null=True)),
                ('time_pb5_elapsed_millisecond_of_day', models.IntegerField(blank=True, null=True)),
                ('gap_flag', models.IntegerField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('sc_pos_gse_x', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_y', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gse_z', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_x', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_y', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_gsm_z', load_cdf.models.Float32Field(blank=True, null=True)),
                ('sc_pos_r', load_cdf.models.Float32Field(blank=True, null=True)),
                ('dqf', models.IntegerField(blank=True, null=True)),
                ('qf_v', models.IntegerField(blank=True, null=True)),
                ('qf_vth', models.IntegerField(blank=True, null=True)),
                ('thermal_spd', load_cdf.models.Float32Field(blank=True, null=True)),
                ('np', load_cdf.models.Float32Field(blank=True, null=True)),
                ('alpha_percent', load_cdf.models.Float32Field(blank=True, null=True)),
                ('qf_np', models.IntegerField(blank=True, null=True)),
                ('qf_ap', models.IntegerField(blank=True, null=True)),
                ('v_gse_vx', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_vy', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_vz', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gsm_vx', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gsm_vy', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gsm_vz', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_p_flow_speed', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_p_ew_flow', load_cdf.models.Float32Field(blank=True, null=True)),
                ('v_gse_p_ns_flow', load_cdf.models.Float32Field(blank=True, null=True)),
                ('cdf_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WIND_WI_K0_SWE_v01_data_data', to='load_cdf.cdffilestored')),
            ],
        ),
    ]
